default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: myrailsapp_user
  password: password
  host: localhost

development:
  <<: *default
  database: myrailsapp_development

test:
  <<: *default
  database: myrailsapp_test
